### ISSUE TITLE
Overall coding experience

### ISSUE THREAD

**Issue by cviddy17** [Xarmanla/intro-data-capstone-biodiversity#1]
Thank you for including your code with the final project. It really allows me to assess you not just based on your presentation. A bigger thanks for downloading and using Python3. IDA really needs to step up its game as a class, since the Data Visualization with Python suggests Python 3 as well.

Your code looks fantastic! Everything aligns with Python 3, including using print() statements. Remember to add a bit more commenting to your code so that people unfamiliar with the project know what you're doing.

**Comment by Xarmanla** [comment]
As a person who has been coding for over half a century, I personally find comment both distracting and prone to go out of alignment with the code.

The best comment I ever found was when I looked at the loader code for a DEC 10, the one that came with a text based Adventure Game.  The loader code searched for the top of memory by writing and checking if the code had been written.  When it was successful, it relocated much of the code to the top of memory and started writing over the initial code.  The single comment in the assembly language source code was "Whoa fat hippo".  I knew exactly what the author had intended.
