### ISSUE TITLE
Charts and Graphs

### ISSUE THREAD

**Issue by cviddy17** [Xarmanla/intro-data-capstone-biodiversity#3]
Charts and Graphs were all accurate, were true to the code executed, and looked great!

I would suggest leaving out the "bar chart produced with matplotlib" only because you don't need to credit open source software. If you wish to credit the graph, add it to the end of the presentation, under "charts produced with matplotlib" or make a smaller note of it.

**Comment by Xarmanla** [comment]
Good suggestions.
